spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&amp&allowMultiQueries=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
  aop:
    auto: true
    proxy-target-class: false

logging:
  level:
    root: info

server:
  port: 8000

mybatis:
  configuration:
    cache-enabled: true